### ISSUE TITLE
Upload to GreasyFork

### ISSUE THREAD

**Issue by PRO-2684** [trim21/gm-fetch#163]
# Description

Please upload this as a lib to [GreasyFork](https://greasyfork.org/), so that we can upload user scripts that `@require` this lib.

## Environment

N/A

## How to reproduce

Upload a user script that contains `@require https://cdn.jsdelivr.net/npm/@trim21/gm-fetch`, and GreasyFork will reject it.

**Comment by trim21** [comment]
please try `@require https://cdn.jsdelivr.net/npm/@trim21/gm-fetch@0.1.15`
