### ISSUE TITLE
Confused about the signal abort line

### ISSUE THREAD

**Issue by JenieX** [trim21/gm-fetch#56]
At this [line](https://github.com/trim21/gm-fetch/blob/46ea71e16baaee8ed14c8b460c859f7a122b4bf7/src/index.ts#L16) in the source, which I just noticed, there is a signal check, which I wish we would have like the normal `fetch`. I'm confused because to my understanding, `GM.` functions are promises, therefor `GM.xmlHttpRequest` can't be aborted.

Would be awesome to clear that up for me.

Note: I'm using an old version because I like it better. 😄

**Comment by trim21** [comment]
You are partially correct, `GM.xmlHttpRequest` can't be aborted but it doesn't return a `Promise`, it's a event callback style object.

That's why I write this in readme:

> And AbortSignal is not supported very well due to the limitation of `GM.xmlHttpRequest`

**Comment by JenieX** [comment]
> You are partially correct, `GM.xmlHttpRequest` can't be aborted but it doesn't return a `Promise`, it's a event callback style object.
> 
> It doesn't have much difference with `GM_xmlHttpRequest`
> 
> That's why I write this in readme:
> 
> > And AbortSignal is not supported very well due to the limitation of `GM.xmlHttpRequest`
> 
> `AbortSignal` is part of `fetch` API and I don't know how to fully support it.
> 
> https://github.com/trim21/gm-fetch/blob/46ea71e16baaee8ed14c8b460c859f7a122b4bf7/src/index.ts#L26
> 
> > Note: I'm using an old version because I like it better. 😄
> 
> I think if makes no difference if you don't pass an `AbortSignal` paramater...

Thank you for clearing that up. I just wanted to make sure that `GM.xmlHttpRequest` can't be aborted.

**Comment by trim21** [comment]
> I just wanted to make sure that GM.xmlHttpRequest can't be aborted.

Actually you can... In some platform

https://www.tampermonkey.net/documentation.php?locale=en#api:GM_xmlhttpRequest


```js
// ==UserScript==
// @name         swagger doc style
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://example.com/*
// @grant        GM_addStyle
// @grant        GM.xmlHttpRequest
// @grant        GM_xmlhttpRequest
// @run-at       document-start
// ==/UserScript==

const r=GM.xmlHttpRequest()

console.log(typeof r.abort)
```

**Comment by JenieX** [comment]
> > I just wanted to make sure that GM.xmlHttpRequest can't be aborted.
> 
> Actually you can... In some platform
> 
> https://www.tampermonkey.net/documentation.php?locale=en#api:GM_xmlhttpRequest
> 
> ```js
> // ==UserScript==
> // @name         swagger doc style
> // @namespace    http://tampermonkey.net/
> // @version      0.1
> // @description  try to take over the world!
> // @author       You
> // @match        https://example.com/*
> // @grant        GM_addStyle
> // @grant        GM.xmlHttpRequest
> // @grant        GM_xmlhttpRequest
> // @run-at       document-start
> // ==/UserScript==
> 
> const r=GM.xmlHttpRequest()
> 
> console.log(typeof r.abort)
> ```
> 
> It's not standard so I didn't support it.
> 
> Do you need this feature? or you are trying to avoid it.

Just tested it in Violentmonkey. It does work. That sure can be useful some day. 😃
I always thought `GM.xmlHttpRequest` of Violentmonkey acted the same way as in Greasemonkey.

https://github.com/greasemonkey/greasemonkey/issues/3142#issue-1247419503
https://wiki.greasespot.net/GM.xmlHttpRequest
